### ISSUE TITLE
Scrum Report #2

### ISSUE THREAD

**Issue by tendy-s** [tendy-s/OutDoorly#13]
Each individual needs to post their scrum report as a comment on this issue:

**Questions your comment should answer:

What did you work on this past iteration (2 weeks)?
What were any major issues/challenges you ran into?
What do you plan to work on for this coming iteration (2 weeks)?**

Rubric:
2: Includes all 3 points. Demonstrates a bit of meaningful reflection on at least one item in the report.
1: Simplistic, or no meaningful, specific information.
0: Missing or Late.

**Comment by tendy-s** [comment]
Name: Tendy Su
csid: f7p0u

What did you work on this past iteration (2 weeks)?

This past iteration I outlined and implemented a number of components for the frontend (e.g. user preferences form, search results, park details), addressed a few styling and alignment issues and used our national parks API to test and display information that's meaningful to our app.

What were any major issues/challenges you ran into? 

In terms of learning challenges, it was my first time working with redux. I found it a bit confusing initially but eventually learned to appreciate its capabilities and incorporated it as a means for our user preferences form to share state and display data with search results. 

What do you plan to work on for this coming iteration (2 weeks)?**

For this coming iteration, I plan to further refine and build out certain UI components: update the workflow for how a user could find parks (generally by distance or more specifically through answering our questions), implement feedback messages and create more relevant filtering/sorting/editing/adding actions to manipulate our redux store, while also incorporating thunking as appropriate.

**Comment by betternick** [comment]
Name: Syed Waqar Ahmed
CSID: a2o6b

**What did you work on this past iteration (2 weeks)?**

This past iteration I spent some time learning about MongoDB. Based on what I had learned, I designed the schema for Parks, which will be the main collection in our database. I also scraped the data we needed from the external national parks API and saved it locally for use i our database.

**What were any major issues/challenges you ran into?**

I was experiencing an issue populating the database as we kept running into validation errors. However, working with my group mates, we did pair programming and were able to debug the issues and got the saved data to populate into our database. 

**What do you plan to work on for this coming iteration (2 weeks)?**

In the coming iteration I will be building routers, controllers and DAOS for different endpoints. One of the endpoints will receive user coordinates params and a chosen radius from the frontend, and build a function that returns all national parks that are within the selected radius. of the user's location

**Comment by dong-michael** [comment]
Name: Michael Dong
CSID: f2m2e

What did you work on this past iteration (2 weeks)?

In this past iteration I worked on populating the local database with information retrieved from the parks API, and I also worked on creating the parksController and parksDao functionality for querying.

What were any major issues/challenges you ran into?

The structuring of the project folders were initially confusing but was resolved with further research into node/mongoose/express applications. Mongoose query syntax can be tricky at times, but all issues were resolved by taking a closer look at the mongoose docs.

What do you plan to work on for this coming iteration (2 weeks)?**

For this coming iteration I plan to work on setting up express for project and creating more endpoints that can be used by the front end.  I will also be looking into possibly adding user login information into the database.

**Comment by babakhadady** [comment]
Name: Babak Hadady
csid: y9m6h

What did you work on this past iteration (2 weeks)?

This past iteration I outlined and worked on several of our Modals, such as the Photo and Review Modals. I also worked on polishing several components up and fixed several bugs, such as our navbar shadow and onhover opacity.

What were any major issues/challenges you ran into?

It was a little difficult to get adjusted to the workflow of the new application, since the process seemed daunting and it wasn't apparent on where to get started. Once I familiarized myself more with our structure and my understanding of what our goals were solidified, it was a lot easier for me to get into a more consistent workflow. 

What do you plan to work on for this coming iteration (2 weeks)?**

For this upcoming iteration, i'm planning on continuing to implement and polish several features, incorporate thunking into our application for back-end support, and hopefully begin to utilize our backend once several of our endpoints are implemented.

**Comment by h-xi** [comment]
Name: Has (Hai Xin) Xi
CSID: Z3J4E

What did you work on this past iteration (2 weeks)?
- Wrote logic and designed database schema and endpoints for backend. 
- Provided guidance on logic for endpoints and database query 
- Helped establish infrastructure for mongoose and database connection/access
What were any major issues/challenges you ran into?
- Getting all members on the same page for database setup 
- Embedding vs referencing for multiple schemas 
What do you plan to work on for this coming iteration (2 weeks)?**
- Express setup 
- pagination
